/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as ProtectedWarehouseSetupRouteImport } from './routes/_protected/warehouse-setup'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedInventoryIndexRouteImport } from './routes/_protected/inventory/index'
import { Route as ProtectedInventoryIdRouteImport } from './routes/_protected/inventory/$id'
import { Route as ProtectedInventoryWarehousesIndexRouteImport } from './routes/_protected/inventory/warehouses/index'
import { Route as ProtectedInventoryWarehousesIdRouteImport } from './routes/_protected/inventory/warehouses/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWarehouseSetupRoute = ProtectedWarehouseSetupRouteImport.update({
  id: '/warehouse-setup',
  path: '/warehouse-setup',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInventoryIndexRoute = ProtectedInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInventoryIdRoute = ProtectedInventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInventoryWarehousesIndexRoute =
  ProtectedInventoryWarehousesIndexRouteImport.update({
    id: '/inventory/warehouses/',
    path: '/inventory/warehouses/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInventoryWarehousesIdRoute =
  ProtectedInventoryWarehousesIdRouteImport.update({
    id: '/inventory/warehouses/$id',
    path: '/inventory/warehouses/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/settings': typeof ProtectedSettingsRoute
  '/warehouse-setup': typeof ProtectedWarehouseSetupRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/inventory/$id': typeof ProtectedInventoryIdRoute
  '/inventory/': typeof ProtectedInventoryIndexRoute
  '/inventory/warehouses/$id': typeof ProtectedInventoryWarehousesIdRoute
  '/inventory/warehouses/': typeof ProtectedInventoryWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/settings': typeof ProtectedSettingsRoute
  '/warehouse-setup': typeof ProtectedWarehouseSetupRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/': typeof ProtectedIndexRoute
  '/inventory/$id': typeof ProtectedInventoryIdRoute
  '/inventory': typeof ProtectedInventoryIndexRoute
  '/inventory/warehouses/$id': typeof ProtectedInventoryWarehousesIdRoute
  '/inventory/warehouses': typeof ProtectedInventoryWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/warehouse-setup': typeof ProtectedWarehouseSetupRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/inventory/$id': typeof ProtectedInventoryIdRoute
  '/_protected/inventory/': typeof ProtectedInventoryIndexRoute
  '/_protected/inventory/warehouses/$id': typeof ProtectedInventoryWarehousesIdRoute
  '/_protected/inventory/warehouses/': typeof ProtectedInventoryWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/warehouse-setup'
    | '/accept-invitation/$id'
    | '/inventory/$id'
    | '/inventory/'
    | '/inventory/warehouses/$id'
    | '/inventory/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/warehouse-setup'
    | '/accept-invitation/$id'
    | '/'
    | '/inventory/$id'
    | '/inventory'
    | '/inventory/warehouses/$id'
    | '/inventory/warehouses'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_protected/settings'
    | '/_protected/warehouse-setup'
    | '/accept-invitation/$id'
    | '/_protected/'
    | '/_protected/inventory/$id'
    | '/_protected/inventory/'
    | '/_protected/inventory/warehouses/$id'
    | '/_protected/inventory/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/warehouse-setup': {
      id: '/_protected/warehouse-setup'
      path: '/warehouse-setup'
      fullPath: '/warehouse-setup'
      preLoaderRoute: typeof ProtectedWarehouseSetupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/': {
      id: '/_protected/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof ProtectedInventoryIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/$id': {
      id: '/_protected/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof ProtectedInventoryIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/warehouses/': {
      id: '/_protected/inventory/warehouses/'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses/'
      preLoaderRoute: typeof ProtectedInventoryWarehousesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/warehouses/$id': {
      id: '/_protected/inventory/warehouses/$id'
      path: '/inventory/warehouses/$id'
      fullPath: '/inventory/warehouses/$id'
      preLoaderRoute: typeof ProtectedInventoryWarehousesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedWarehouseSetupRoute: typeof ProtectedWarehouseSetupRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedInventoryIdRoute: typeof ProtectedInventoryIdRoute
  ProtectedInventoryIndexRoute: typeof ProtectedInventoryIndexRoute
  ProtectedInventoryWarehousesIdRoute: typeof ProtectedInventoryWarehousesIdRoute
  ProtectedInventoryWarehousesIndexRoute: typeof ProtectedInventoryWarehousesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedWarehouseSetupRoute: ProtectedWarehouseSetupRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedInventoryIdRoute: ProtectedInventoryIdRoute,
  ProtectedInventoryIndexRoute: ProtectedInventoryIndexRoute,
  ProtectedInventoryWarehousesIdRoute: ProtectedInventoryWarehousesIdRoute,
  ProtectedInventoryWarehousesIndexRoute:
    ProtectedInventoryWarehousesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
