/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedEntitiesIndexRouteImport } from './routes/_protected/entities/index'
import { Route as ProtectedDocumentsIndexRouteImport } from './routes/_protected/documents/index'
import { Route as ProtectedCatalogIndexRouteImport } from './routes/_protected/catalog/index'
import { Route as ProtectedEntitiesIdRouteImport } from './routes/_protected/entities/$id'
import { Route as ProtectedDocumentsIdRouteImport } from './routes/_protected/documents/$id'
import { Route as ProtectedCatalogIdRouteImport } from './routes/_protected/catalog/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEntitiesIndexRoute = ProtectedEntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentsIndexRoute = ProtectedDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCatalogIndexRoute = ProtectedCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEntitiesIdRoute = ProtectedEntitiesIdRouteImport.update({
  id: '/entities/$id',
  path: '/entities/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentsIdRoute = ProtectedDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCatalogIdRoute = ProtectedCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/settings': typeof ProtectedSettingsRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/catalog/$id': typeof ProtectedCatalogIdRoute
  '/documents/$id': typeof ProtectedDocumentsIdRoute
  '/entities/$id': typeof ProtectedEntitiesIdRoute
  '/catalog/': typeof ProtectedCatalogIndexRoute
  '/documents/': typeof ProtectedDocumentsIndexRoute
  '/entities/': typeof ProtectedEntitiesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/settings': typeof ProtectedSettingsRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/': typeof ProtectedIndexRoute
  '/catalog/$id': typeof ProtectedCatalogIdRoute
  '/documents/$id': typeof ProtectedDocumentsIdRoute
  '/entities/$id': typeof ProtectedEntitiesIdRoute
  '/catalog': typeof ProtectedCatalogIndexRoute
  '/documents': typeof ProtectedDocumentsIndexRoute
  '/entities': typeof ProtectedEntitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/catalog/$id': typeof ProtectedCatalogIdRoute
  '/_protected/documents/$id': typeof ProtectedDocumentsIdRoute
  '/_protected/entities/$id': typeof ProtectedEntitiesIdRoute
  '/_protected/catalog/': typeof ProtectedCatalogIndexRoute
  '/_protected/documents/': typeof ProtectedDocumentsIndexRoute
  '/_protected/entities/': typeof ProtectedEntitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/accept-invitation/$id'
    | '/catalog/$id'
    | '/documents/$id'
    | '/entities/$id'
    | '/catalog/'
    | '/documents/'
    | '/entities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/accept-invitation/$id'
    | '/'
    | '/catalog/$id'
    | '/documents/$id'
    | '/entities/$id'
    | '/catalog'
    | '/documents'
    | '/entities'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_protected/settings'
    | '/accept-invitation/$id'
    | '/_protected/'
    | '/_protected/catalog/$id'
    | '/_protected/documents/$id'
    | '/_protected/entities/$id'
    | '/_protected/catalog/'
    | '/_protected/documents/'
    | '/_protected/entities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/entities/': {
      id: '/_protected/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof ProtectedEntitiesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/documents/': {
      id: '/_protected/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof ProtectedDocumentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/catalog/': {
      id: '/_protected/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof ProtectedCatalogIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/entities/$id': {
      id: '/_protected/entities/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof ProtectedEntitiesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/documents/$id': {
      id: '/_protected/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof ProtectedDocumentsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/catalog/$id': {
      id: '/_protected/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof ProtectedCatalogIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedCatalogIdRoute: typeof ProtectedCatalogIdRoute
  ProtectedDocumentsIdRoute: typeof ProtectedDocumentsIdRoute
  ProtectedEntitiesIdRoute: typeof ProtectedEntitiesIdRoute
  ProtectedCatalogIndexRoute: typeof ProtectedCatalogIndexRoute
  ProtectedDocumentsIndexRoute: typeof ProtectedDocumentsIndexRoute
  ProtectedEntitiesIndexRoute: typeof ProtectedEntitiesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedCatalogIdRoute: ProtectedCatalogIdRoute,
  ProtectedDocumentsIdRoute: ProtectedDocumentsIdRoute,
  ProtectedEntitiesIdRoute: ProtectedEntitiesIdRoute,
  ProtectedCatalogIndexRoute: ProtectedCatalogIndexRoute,
  ProtectedDocumentsIndexRoute: ProtectedDocumentsIndexRoute,
  ProtectedEntitiesIndexRoute: ProtectedEntitiesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
