// AUTO-GENERATED by `pnpm --filter @workspace/registry generate`. Do not edit by hand.
import { lazy } from "react";
import type { RegistryEntry } from "./types";

export const REGISTRY: Record<string, RegistryEntry> = {
  "accept-invite": {
    name: "accept-invite",
    type: "registry:block",
    title: "Accept invite",
    description:
      "Centered invite-acceptance route — org + role context over a name + password card, zod-validated.",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(() => import("../registry/blocks/accept-invite/page")),
  },
  "chat-page": {
    name: "chat-page",
    type: "registry:block",
    title: "Chat page",
    description:
      "Full-screen assistant chat inside the app shell — conversation, prompt input, and mock replies.",
    meta: { sfabKind: "block", iframeHeight: 900 },
    component: lazy(() => import("../registry/blocks/chat-page/page")),
  },
  "coming-soon-page": {
    name: "coming-soon-page",
    type: "registry:block",
    title: "Coming soon page",
    description:
      "Honest full-page states — coming soon, not found, and empty — for routes that aren't built or have no data yet.",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(
      () => import("../registry/blocks/coming-soon-page/preview")
    ),
  },
  "command-palette": {
    name: "command-palette",
    type: "registry:block",
    title: "Command palette",
    description:
      "⌘K / sidebar search — go-to navigation from navigation-config (no faked entity search).",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(() => import("../registry/blocks/command-palette/page")),
  },
  "destructive-confirm": {
    name: "destructive-confirm",
    type: "registry:block",
    title: "Destructive confirm",
    description:
      "The default destructive confirm — one AlertDialog with Cancel / Delete, then a post-commit toast.",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(
      () => import("../registry/blocks/destructive-confirm/page")
    ),
  },
  "markdown-editor": {
    name: "markdown-editor",
    type: "registry:ui",
    title: "Markdown editor",
    description:
      "BlockNote WYSIWYG markdown editor — controlled value/onChange, trimmed formatting toolbar, theme-aware, layout-neutral.",
    meta: { sfabKind: "block" },
    component: lazy(
      () =>
        import("../registry/components/markdown-editor/markdown-editor-demo")
    ),
  },
  "pdf-viewer": {
    name: "pdf-viewer",
    type: "registry:ui",
    title: "PDF viewer",
    description:
      "Continuous fit-to-width PDF reader on react-pdf (pdf.js) — scroll, zoom, page X of N, loading/error states, layout-neutral.",
    meta: { sfabKind: "block" },
    component: lazy(
      () => import("../registry/components/pdf-viewer/pdf-viewer-demo")
    ),
  },
  "record-edit-page": {
    name: "record-edit-page",
    type: "registry:block",
    title: "Record edit page",
    description:
      "Invoice edit route — due date and notes form on a full shell page with activity log.",
    meta: { sfabKind: "block", iframeHeight: 900 },
    component: lazy(() => import("../registry/blocks/record-edit-page/page")),
  },
  "record-payment-dialog": {
    name: "record-payment-dialog",
    type: "registry:block",
    title: "Record payment dialog",
    description:
      "Collect hub with record-payment dialog open by default — money fields plus activity log (MXN minor units).",
    meta: { sfabKind: "block", iframeHeight: 900 },
    component: lazy(
      () => import("../registry/blocks/record-payment-dialog/page")
    ),
  },
  "record-read-page": {
    name: "record-read-page",
    type: "registry:block",
    title: "Record read page",
    description:
      "Invoice record route — PropertyGrid and activity log on a full shell page (read-only).",
    meta: { sfabKind: "block", iframeHeight: 900 },
    component: lazy(() => import("../registry/blocks/record-read-page/page")),
  },
  "resource-list-page": {
    name: "resource-list-page",
    type: "registry:block",
    title: "Resource list page",
    description:
      "Full list page — app shell, list page shell, filter toolbar, resource table, and a React Query hook on mock data.",
    meta: { sfabKind: "block", iframeHeight: 900 },
    component: lazy(
      () => import("../registry/blocks/resource-list-page/preview")
    ),
  },
  "resource-table": {
    name: "resource-table",
    type: "registry:ui",
    title: "Resource table",
    description:
      "Extended DataTable with drill-in row click, inline CTA, and kebab actions.",
    meta: { sfabKind: "block" },
    component: lazy(
      () => import("../registry/components/resource-table/resource-table-demo")
    ),
  },
  "settings-page": {
    name: "settings-page",
    type: "registry:block",
    title: "Settings page",
    description:
      "Full-route org settings — organization details, member invites, members table, and pending invitations (gallery mock, admin+ surface).",
    meta: { sfabKind: "block", iframeHeight: 900 },
    component: lazy(() => import("../registry/blocks/settings-page/page")),
  },
  shell: {
    name: "shell",
    type: "registry:ui",
    title: "Shell",
    description:
      "App shell compound layout — sidebar frame, page header row, and main content slot.",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(() => import("../registry/components/shell/shell-demo")),
  },
  "sign-in": {
    name: "sign-in",
    type: "registry:block",
    title: "Sign in",
    description:
      "Centered sign-in route — brand mark over an email + password card, zod-validated.",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(() => import("../registry/blocks/sign-in/page")),
  },
  "sign-up": {
    name: "sign-up",
    type: "registry:block",
    title: "Sign up",
    description:
      "Centered sign-up route — name, email, and password card on the shared auth shell, zod-validated.",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(() => import("../registry/blocks/sign-up/page")),
  },
  "spreadsheet-viewer": {
    name: "spreadsheet-viewer",
    type: "registry:ui",
    title: "Spreadsheet viewer",
    description:
      "Read-only .xlsx viewer on Univer (open-source Luckysheet successor) with the client-side LuckyExcel importer — styles, merges, formulas, theme-aware, layout-neutral.",
    meta: { sfabKind: "block" },
    component: lazy(
      () =>
        import(
          "../registry/components/spreadsheet-viewer/spreadsheet-viewer-demo"
        )
    ),
  },
  "today-overview": {
    name: "today-overview",
    type: "registry:block",
    title: "Today overview",
    description:
      "Operator home — primary actions, honest KPI tiles, and action items.",
    meta: { sfabKind: "block", iframeHeight: 900 },
    component: lazy(() => import("../registry/blocks/today-overview/page")),
  },
  "type-to-confirm": {
    name: "type-to-confirm",
    type: "registry:block",
    title: "Type-to-confirm",
    description:
      "The highest-stakes destroy guard — a dialog whose Delete button unlocks only once the operator types the resource's exact name.",
    meta: { sfabKind: "block", iframeHeight: 720 },
    component: lazy(() => import("../registry/blocks/type-to-confirm/page")),
  },
};
