// AUTO-GENERATED by `pnpm --filter @workspace/registry generate`. Do not edit by hand.
import { lazy } from "react";
import type { RegistryEntry } from "./types";

export const REGISTRY: Record<string, RegistryEntry> = {
  badge: {
    name: "badge",
    type: "registry:ui",
    title: "Badge",
    description: "Status labels in every variant.",
    meta: { sfabKind: "block" },
    component: lazy(() => import("../registry/badge/badge-demo")),
  },
  button: {
    name: "button",
    type: "registry:ui",
    title: "Button",
    description: "Variants, sizes, icon, and disabled states.",
    meta: { sfabKind: "block" },
    component: lazy(() => import("../registry/button/button-demo")),
  },
  "dashboard-01": {
    name: "dashboard-01",
    type: "registry:block",
    title: "Operator dashboard",
    description:
      "The full app shell — collapsible sidebar, header, stat cards, a data table, and an activity feed.",
    meta: { sfabKind: "block", iframeHeight: 860 },
    component: lazy(() => import("../registry/dashboard-01/page")),
  },
};
