// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
// biome-ignore lint/performance/noNamespaceImport: It ok for index registry
import * as React from "react";

export const Index: Record<string, any> = {
  "app-layout": {
    name: "app-layout",
    description:
      "A comprehensive layout system with sidebar navigation, resizable panels, and organized content areas.",
    type: "registry:ui",
    registryDependencies: ["button", "resizable", "separator", "sidebar"],
    files: [
      {
        path: "../ui/src/components/brand/app-layout.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@workspace/ui/components/brand/app-layout");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "app-layout";
      return { default: mod.default || mod[exportName] };
    }),
    categories: [],
    meta: {
      examples: [
        {
          name: "app-layout-basic",
          title: "Basic Layout",
          description: "Simple layout with header and content using AppSidebar",
        },
        {
          name: "app-layout-no-header",
          title: "Layout Without Header",
          description: "Minimal layout without header for cleaner interfaces",
        },
      ],
    },
  },
  "app-01": {
    name: "app-01",
    description:
      "An example app layout with a sidebar and a main content area.",
    type: "registry:block",
    registryDependencies: ["button"],
    files: [
      {
        path: "./src/components/blocks/app-01/page.tsx",
        type: "registry:block",
        target: "",
      },
      {
        path: "./src/components/blocks/app-01/components/app-sidebar.tsx",
        type: "registry:block",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@workspace/ui-ds/components/blocks/app-01/page"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "app-01";
      return { default: mod.default || mod[exportName] };
    }),
    categories: [],
    meta: {},
  },
  "app-layout-basic": {
    name: "app-layout-basic",
    description: "Simple layout with header and content using AppSidebar",
    type: "registry:example",
    registryDependencies: [],
    files: [
      {
        path: "./src/components/examples/app-layout-basic.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@workspace/ui-ds/components/examples/app-layout-basic"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "app-layout-basic";
      return { default: mod.default || mod[exportName] };
    }),
    categories: [],
    meta: {},
  },
  "app-layout-no-header": {
    name: "app-layout-no-header",
    description: "Minimal layout without header for cleaner interfaces",
    type: "registry:example",
    registryDependencies: [],
    files: [
      {
        path: "./src/components/examples/app-layout-no-header.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@workspace/ui-ds/components/examples/app-layout-no-header"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "app-layout-no-header";
      return { default: mod.default || mod[exportName] };
    }),
    categories: [],
    meta: {},
  },
};
