/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ../../packages/env/src/env.d.ts` (hash: de1b9b32bd4f205a9d4da4999db6e307)
interface __BaseEnv_Env {
	R2_BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	RESEND_API_KEY: string;
	EMAIL_SENDER: string;
	MOCK_SEND_EMAIL: string;
	ORG_CHAT_PROVIDER: string;
	ZAI_API_KEY: string;
	AI_GATEWAY_API_KEY: string;
	ELEVENLABS_API_KEY: string;
	OrgAgent: DurableObjectNamespace;
	VoiceLabAgent: DurableObjectNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "RESEND_API_KEY" | "EMAIL_SENDER" | "MOCK_SEND_EMAIL" | "ORG_CHAT_PROVIDER" | "ZAI_API_KEY" | "AI_GATEWAY_API_KEY" | "ELEVENLABS_API_KEY">> {}
}
