/* eslint-disable */
// Generated by Wrangler by running `wrangler types ../../packages/env/src/env.d.ts --include-runtime=false` (hash: 3bdec81892046b0a4ec88448b48d474f)
declare namespace Cloudflare {
	interface Env {
		R2_BUCKET: R2Bucket;
		DB: D1Database;
		LOADER: WorkerLoader;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		RESEND_API_KEY: string;
		EMAIL_SENDER: string;
		MOCK_SEND_EMAIL: string;
		ORG_CHAT_PROVIDER: string;
		ZAI_API_KEY: string;
		OrgAgent: DurableObjectNamespace;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "RESEND_API_KEY" | "EMAIL_SENDER" | "MOCK_SEND_EMAIL" | "ORG_CHAT_PROVIDER" | "ZAI_API_KEY">> {}
}
