/* eslint-disable */
// Generated by Wrangler by running `wrangler types ../../packages/env/src/env.d.ts --include-runtime=false` (hash: d7221b21192fc102f4aca8688be2af02)
declare namespace Cloudflare {
	interface Env {
		R2_BUCKET: R2Bucket;
		DB: D1Database;
		LOADER: WorkerLoader;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		RESEND_API_KEY: string;
		EMAIL_SENDER: string;
		MOCK_SEND_EMAIL: string;
		OrgAgent: DurableObjectNamespace;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "RESEND_API_KEY" | "EMAIL_SENDER" | "MOCK_SEND_EMAIL">> {}
}
