/* eslint-disable */
// Generated by Wrangler by running `wrangler types ../../packages/cloudflare-env/src/env.d.ts --include-runtime=false` (hash: 155073c59b8cf6bbf120a458dca66306)
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		AI_GATEWAY_API_KEY: string;
		RESEND_API_KEY: string;
		EMAIL_SENDER: string;
		MOCK_SEND_EMAIL: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "AI_GATEWAY_API_KEY" | "RESEND_API_KEY" | "EMAIL_SENDER" | "MOCK_SEND_EMAIL">> {}
}
