import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { RegistryItemDef } from "../src/types";

/**
 * Generates the two derived artifacts from the `registry/<name>/` source trees,
 * which are the single source of truth (ADR-0017 amendment, RD-7):
 *
 *   1. the repo-root `registry.json` (the shadcn GitHub-registry manifest), and
 *   2. `src/generated.ts` (the gallery's `name -> { ...meta, lazy component }` map).
 *
 * Each item directory contributes one `item.ts` (its shadcn `RegistryItem` +
 * `preview` entrypoint, authored with item-relative file paths). Run with
 * `--check` to fail (non-zero) if either artifact is stale — the CI drift gate.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = join(HERE, "..");
const REPO_ROOT = join(PKG_ROOT, "..", "..");
const ITEMS_DIR = join(PKG_ROOT, "registry");

/** Where the package's item trees live, relative to the repo root. */
const REPO_PREFIX = "packages/registry/registry";
const HOMEPAGE = "https://github.com/sfab-oss/sfab-starter";

const REGISTRY_JSON = join(REPO_ROOT, "registry.json");
const GENERATED_TS = join(PKG_ROOT, "src", "generated.ts");

interface LoadedDef {
  name: string;
  def: RegistryItemDef;
}

async function loadDefs(): Promise<LoadedDef[]> {
  const names = readdirSync(ITEMS_DIR, { withFileTypes: true })
    .filter(
      (d) => d.isDirectory() && existsSync(join(ITEMS_DIR, d.name, "item.ts"))
    )
    .map((d) => d.name)
    .sort();

  const defs: LoadedDef[] = [];
  for (const name of names) {
    const href = pathToFileURL(join(ITEMS_DIR, name, "item.ts")).href;
    const mod = (await import(href)) as { default: RegistryItemDef };
    const def = mod.default;
    for (const file of def.item.files ?? []) {
      const abs = join(ITEMS_DIR, name, file.path);
      if (!existsSync(abs)) {
        throw new Error(`${name}: file not found on disk: ${file.path}`);
      }
    }
    defs.push({ name, def });
  }
  return defs;
}

function buildRegistryJson(defs: LoadedDef[]): string {
  const items = defs.map(({ name, def }) => ({
    ...def.item,
    files: (def.item.files ?? []).map((f) => ({
      ...f,
      path: `${REPO_PREFIX}/${name}/${f.path}`,
    })),
  }));
  const manifest = {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "sfab-starter",
    homepage: HOMEPAGE,
    items,
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function buildGeneratedTs(defs: LoadedDef[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by `pnpm --filter @workspace/registry generate`. Do not edit by hand.",
    'import { lazy } from "react";',
    'import type { RegistryEntry } from "./types";',
    "",
    "export const REGISTRY: Record<string, RegistryEntry> = {",
  ];
  for (const { name, def } of defs) {
    const { item, preview } = def;
    const importPath = `../registry/${name}/${preview}`;
    lines.push(`  ${JSON.stringify(name)}: {`);
    lines.push(`    name: ${JSON.stringify(item.name)},`);
    lines.push(`    type: ${JSON.stringify(item.type)},`);
    if (item.title !== undefined) {
      lines.push(`    title: ${JSON.stringify(item.title)},`);
    }
    if (item.description !== undefined) {
      lines.push(`    description: ${JSON.stringify(item.description)},`);
    }
    lines.push(`    meta: ${JSON.stringify(item.meta)},`);
    lines.push(
      `    component: lazy(() => import(${JSON.stringify(importPath)})),`
    );
    lines.push("  },");
  }
  lines.push("};", "");
  return lines.join("\n");
}

/**
 * Run the raw output through the repo's biome (the same `check --write` that
 * formats every other file) so the committed artifact and a fresh generation are
 * byte-identical — the drift check then never trips on a pure reformat.
 */
function format(path: string, content: string): string {
  return execFileSync(
    "pnpm",
    ["exec", "biome", "check", "--write", `--stdin-file-path=${path}`],
    { input: content, encoding: "utf8", cwd: REPO_ROOT }
  );
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const defs = await loadDefs();
  const artifacts: Array<{ path: string; content: string }> = [
    {
      path: REGISTRY_JSON,
      content: format(REGISTRY_JSON, buildRegistryJson(defs)),
    },
    {
      path: GENERATED_TS,
      content: format(GENERATED_TS, buildGeneratedTs(defs)),
    },
  ];

  if (check) {
    const stale = artifacts.filter((a) => {
      const onDisk = existsSync(a.path) ? readFileSync(a.path, "utf8") : "";
      return onDisk !== a.content;
    });
    if (stale.length > 0) {
      for (const a of stale) {
        process.stderr.write(`stale: ${a.path}\n`);
      }
      process.stderr.write(
        "Registry artifacts are out of date. Run `pnpm --filter @workspace/registry generate`.\n"
      );
      process.exit(1);
    }
    process.stdout.write(`Registry up to date (${defs.length} items).\n`);
    return;
  }

  for (const a of artifacts) {
    writeFileSync(a.path, a.content);
  }
  process.stdout.write(
    `Wrote registry.json + src/generated.ts (${defs.length} items).\n`
  );
}

main().catch((err) => {
  process.stderr.write(`${err instanceof Error ? err.stack : String(err)}\n`);
  process.exit(1);
});
