import { exec } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";

const execAsync = promisify(exec);

// Import registry from the ui-registry directory
const registryModule = await import("../config/index.js");
const { registry } = registryModule;

const REGISTRY_ROOT = path.join(process.cwd(), "src");
const PACKAGE_ROOT = process.cwd(); // packages/ui-ds
const WEB_APP_ROOT = path.join(process.cwd(), "../../apps/web");
const PUBLIC_ROOT = path.join(WEB_APP_ROOT, "public/r");

async function rimraf(path: string) {
  try {
    await fs.rm(path, { recursive: true, force: true });
  } catch {
    // Ignore errors
  }
}

async function buildRegistryIndex() {
  let index = `// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
// biome-ignore lint/performance/noNamespaceImport: It ok for index registry
import * as React from "react"

export const Index: Record<string, any> = {`;

  // Use registry items (examples are already included)
  const allItems = registry.items;

  for (const item of allItems) {
    const resolveFiles = item.files?.map((file) => `registry/${file.path}`);
    if (!resolveFiles || item.files?.length === 0) {
      continue;
    }

    let componentPath = "";
    if (item.files?.[0]?.path) {
      if (item.files[0].path.startsWith("../")) {
        componentPath = `@workspace/ui/components/brand/${item.files[0].path.split("/").pop()?.replace(".tsx", "")}`;
      } else {
        // Use package-absolute import path so it works when imported from other packages
        componentPath = `@workspace/ui-ds/components/${item.files[0].path.replace(".tsx", "")}`;
      }
    }

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies ?? [])},
    files: [${item.files?.map((file) => {
      const filePathValue = typeof file === "string" ? file : file.path;
      const filePath = filePathValue.startsWith("../")
        ? filePathValue
        : `./src/components/${filePathValue}`;
      return typeof file === "string"
        ? `"${filePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories ?? [])},
    meta: ${JSON.stringify(item.meta ?? {})},
  },`;
  }

  index += `
}`;

  console.log(`#️⃣  ${allItems.length} items found`);

  const indexPath = path.join(REGISTRY_ROOT, "__index__.tsx");
  await rimraf(indexPath);
  await fs.writeFile(indexPath, index, "utf-8");
}

async function buildRegistryJsonFile() {
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: file.path.startsWith("../")
            ? file.path
            : `./src/components/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  const registryJsonPath = path.join(PACKAGE_ROOT, "registry.json");
  await rimraf(registryJsonPath);
  await fs.writeFile(
    registryJsonPath,
    JSON.stringify(fixedRegistry, null, 2),
    "utf-8"
  );

  try {
    await execAsync("biome check registry.json --write");
  } catch {
    // Biome might not be available or file might not exist yet
  }

  await fs.mkdir(PUBLIC_ROOT, { recursive: true });
  await fs.cp(registryJsonPath, path.join(PUBLIC_ROOT, "registry.json"), {
    recursive: true,
  });
}

function buildRegistry() {
  return new Promise<void>((resolve, reject) => {
    const childProcess = exec(
      `npx shadcn build registry.json --output ${PUBLIC_ROOT}`,
      {
        cwd: PACKAGE_ROOT,
      }
    );

    childProcess.stdout?.on("data", (data) => {
      console.log(data.toString().trim());
    });

    childProcess.stderr?.on("data", (data) => {
      console.error(data.toString().trim());
    });

    childProcess.on("error", (error) => {
      reject(
        new Error(`Failed to start shadcn build process: ${error.message}`)
      );
    });

    childProcess.on("exit", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`shadcn build process exited with code ${code}`));
      }
    });
  });
}

async function buildBlocksIndex() {
  // Simple blocks index - we'll implement getAllRegistryItems later if needed
  const blocks = registry.items.filter(
    (item) => item.type === "registry:block"
  );

  const payload = blocks.map((block) => ({
    name: block.name,
    description: block.description,
    categories: block.categories,
  }));

  const blocksIndexPath = path.join(REGISTRY_ROOT, "__blocks__.json");
  await rimraf(blocksIndexPath);
  await fs.writeFile(
    blocksIndexPath,
    JSON.stringify(payload, null, 2),
    "utf-8"
  );

  try {
    await execAsync("biome check src/__blocks__.json --write");
  } catch {
    // Biome might not be available
  }
}

try {
  console.log("🗂️ Building registry/__index__.tsx...");
  await buildRegistryIndex();

  console.log("🗂️ Building registry/__blocks__.json...");
  await buildBlocksIndex();

  console.log("💅 Building registry.json...");
  await buildRegistryJsonFile();

  console.log("🏗️ Building registry...");
  await buildRegistry();

  console.log("✅ Registry build complete!");
} catch (error) {
  console.error(error);
  process.exit(1);
}
